# This is the development docker-compose. For production use `docker-compose.prod.yml`.
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: front
    environment:
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - IS_DEV=true
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: always
    develop:
      watch:
        - action: sync
          path: ./back
          target: /app

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3030:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

