services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
