services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        PORT: ${BACKEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
      args:
        PORT: ${BACKEND_PORT}
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

