# This is the development docker-compose. For production use `docker-compose.prod.yml`.
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: front
    environment:
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - IS_DEV=true
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      # Garage configuration
      - GARAGE_ENDPOINT=${GARAGE_ENDPOINT}
      - GARAGE_ACCESS_KEY=${GARAGE_ACCESS_KEY}
      - GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY}
      - GARAGE_BUCKET_NAME=${GARAGE_BUCKET_NAME}
      - GARAGE_REGION=${GARAGE_REGION}
      # R2 configuration
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: always
    develop:
      watch:
        - action: sync
          path: ./back
          target: /app

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3030:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

  garage:
    image: dxflrs/garage:v2.1.0
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    restart: always
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

volumes:
  garage_meta:
  garage_data:
