services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
