FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN npm add -g @nestjs/cli

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 3001

CMD ["pnpm", "start:dev"]
