FROM node:18 AS builder

USER nonroot

ARG PORT
ENV PORT ${PORT}

WORKDIR /app

COPY package*.json ./
RUN npm install --ignore-scripts

COPY next-env.d.ts next.config.ts postcss.config.mjs tsconfig.json src/ public/ ./

RUN npm run build

FROM node:18-slim

USER nonroot

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next .next
COPY --from=builder /app/public public

RUN npm install --omit=dev --ignore-scripts

EXPOSE ${PORT}

CMD ["npm", "run", "start"]
